/**
 * Dashboard metric registry.
 *
 * Each entry tells `<MetricTile />` how to load, transform, and render a
 * single metric. The catalogue in `data/dashboard-metrics.md` is the
 * editorial reference; this file is the runtime spec.
 *
 * Required fields per metric:
 *   id           unique kebab-case
 *   subtab       "service-delivery" | "sovereign-capability" | "construction" | "quality-of-life"
 *   title        tile heading
 *   dataset      filename in /public/data (e.g. "nhs-waiting.json")
 *   seriesKey    key into the unwrapped data object (e.g. "rtt")
 *   timeKey      field within each data row that is the time
 *   valueKey     field within each data row that is the headline value
 *   cadence      "monthly" | "quarterly" | "annual"
 *   direction    "up-good" | "up-bad" | "neutral"
 *   unit         display suffix (e.g. "treatments")
 *   format       "number" | "percent" | "currency" | "raw"
 *   source       citation string
 *
 * Optional:
 *   href            click-through to existing /data page
 *   deltaPctMode    true (default) for percent deltas; false for absolute deltas
 *   periodLabel     map of period-key → label, e.g. { mom: "vs prior month" }
 *   transform       (value, row) => transformedValue (rare)
 */

export const METRICS = {
  // ── Service Delivery ──────────────────────────────────────────────

  "sd-nhs-rtt-waiting-list": {
    id: "sd-nhs-rtt-waiting-list",
    subtab: "service-delivery",
    title: "NHS RTT waiting list",
    dataset: "nhs-waiting.json",
    seriesKey: "rtt",
    timeKey: "period",
    valueKey: "totalWaiting",
    cadence: "monthly",
    direction: "up-bad",
    unit: "treatments",
    format: "number",
    source: "NHS England, RTT",
    href: "/data/foundations/healthcare/waiting",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "sd-gp-appointments": {
    id: "sd-gp-appointments",
    subtab: "service-delivery",
    title: "GP appointments per month",
    dataset: "gp-access.json",
    seriesKey: "appointments",
    timeKey: "month",
    valueKey: "total",
    cadence: "monthly",
    direction: "up-good",
    unit: "millions / month",
    format: "raw",
    source: "NHS Digital — Appointments in General Practice",
    href: "/data/foundations/healthcare/gp",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "sd-hospital-occupancy": {
    id: "sd-hospital-occupancy",
    subtab: "service-delivery",
    title: "Hospital bed occupancy",
    dataset: "hospital-capacity.json",
    seriesKey: "occupancy",
    timeKey: "year",
    valueKey: "overall",
    cadence: "annual",
    direction: "up-bad",
    unit: "%",
    format: "percent",
    source: "NHS England — Bed Availability",
    href: "/data/foundations/healthcare/capacity",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sd-mental-health-iapt": {
    id: "sd-mental-health-iapt",
    subtab: "service-delivery",
    title: "Mental health (IAPT) referrals",
    dataset: "mental-health.json",
    seriesKey: "iaptReferrals",
    timeKey: "quarter",
    valueKey: "referrals",
    cadence: "quarterly",
    direction: "up-good",
    unit: "referrals",
    format: "number",
    source: "NHS Talking Therapies",
    href: "/data/foundations/healthcare/mental",
    periodLabel: { mom: "vs prior quarter", q: "vs prior quarter", y: "vs prior year" },
  },

  "sd-court-backlog": {
    id: "sd-court-backlog",
    subtab: "service-delivery",
    title: "Crown Court outstanding cases",
    dataset: "court-backlog-quarterly.json",
    seriesKey: "quarterly",
    timeKey: "quarter",
    valueKey: "outstanding",
    cadence: "quarterly",
    direction: "up-bad",
    unit: "cases outstanding",
    format: "number",
    source: "MoJ Criminal Court Statistics",
    href: "/data/state/justice",
    periodLabel: { mom: "vs prior quarter", q: "vs prior quarter", y: "vs prior year" },
  },

  "sd-energy-bill": {
    id: "sd-energy-bill",
    subtab: "service-delivery",
    title: "Domestic energy bill (Ofgem cap)",
    dataset: "ofgem-price-cap.json",
    seriesKey: "quarterly",
    timeKey: "quarter",
    valueKey: "annual",
    cadence: "quarterly",
    direction: "up-bad",
    unit: "£ / year (typical household)",
    format: "currency",
    source: "Ofgem default tariff cap",
    href: "/data/foundations/energy",
    periodLabel: { mom: "vs prior quarter", q: "vs prior quarter", y: "vs prior year" },
  },

  "sd-water-leakage": {
    id: "sd-water-leakage",
    subtab: "service-delivery",
    title: "Water leakage",
    dataset: "water.json",
    seriesKey: "leakage",
    timeKey: "year",
    valueKey: "value",
    cadence: "annual",
    direction: "up-bad",
    unit: "Ml / day",
    format: "number",
    source: "Ofwat Water Company Performance Report",
    href: "/data/foundations/water/performance",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sd-rail-punctuality": {
    id: "sd-rail-punctuality",
    subtab: "service-delivery",
    title: "Rail PPM",
    dataset: "infrastructure.json",
    seriesKey: "rail.punctuality",
    timeKey: "year",
    valueKey: "ppm",
    cadence: "annual",
    direction: "up-good",
    unit: "% on time",
    format: "percent",
    source: "ORR Passenger Rail Performance",
    href: "/data/growth/transport/rail",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sd-police-officers": {
    id: "sd-police-officers",
    subtab: "service-delivery",
    title: "Police officers (workforce)",
    dataset: "workforce.json",
    seriesKey: "police",
    timeKey: "year",
    valueKey: "officers",
    cadence: "annual",
    direction: "up-good",
    unit: "thousands",
    format: "number",
    source: "Home Office Police Workforce Statistics",
    href: "/data/state/justice",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sd-prison-population": {
    id: "sd-prison-population",
    subtab: "service-delivery",
    title: "Prison population",
    dataset: "justice.json",
    seriesKey: "prisonPopulation",
    timeKey: "year",
    valueKey: "population",
    cadence: "annual",
    direction: "neutral",
    unit: "thousands",
    format: "number",
    source: "MoJ HMPPS",
    href: "/data/state/justice",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sd-asylum-backlog": {
    id: "sd-asylum-backlog",
    subtab: "service-delivery",
    title: "Asylum decisions backlog",
    dataset: "asylum-statistics.json",
    seriesKey: "asylumBacklogQuarterly",
    timeKey: "quarter",
    valueKey: "pending",
    cadence: "quarterly",
    direction: "up-bad",
    unit: "cases",
    format: "number",
    source: "Home Office, Immigration Statistics",
    href: "/data/state/immigration",
    periodLabel: {
      mom: "vs prior quarter",
      q: "vs prior quarter",
      y: "vs prior year",
    },
  },

  // ── Building ──────────────────────────────────────────────────────

  "bd-housing-completions": {
    id: "bd-housing-completions",
    subtab: "construction",
    title: "Housing completions (England)",
    dataset: "housing-supply.json",
    seriesKey: "netAdditions",
    timeKey: "year",
    valueKey: "dwellings",
    cadence: "annual",
    direction: "up-good",
    unit: "net additions / year",
    format: "number",
    source: "DLUHC Live Table 120",
    href: "/data/foundations/housing/supply",
    periodLabel: {
      mom: "vs prior year",
      q: "vs prior year",
      y: "vs prior year",
    },
  },

  // ── Sovereign Capability ──────────────────────────────────────────

  "sc-army-personnel": {
    id: "sc-army-personnel",
    subtab: "sovereign-capability",
    title: "British Army personnel",
    dataset: "defence.json",
    seriesKey: "personnel",
    timeKey: "year",
    valueKey: "army",
    cadence: "annual",
    direction: "up-good",
    unit: "thousands",
    format: "raw",
    source: "MoD Service Personnel Statistics",
    href: "/data/state/defence/personnel",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sc-naval-escorts": {
    id: "sc-naval-escorts",
    subtab: "sovereign-capability",
    title: "Royal Navy escort fleet",
    dataset: "defence.json",
    seriesKey: "escortFleet",
    timeKey: "year",
    valueKey: "total",
    cadence: "annual",
    direction: "up-good",
    unit: "frigates + destroyers",
    format: "number",
    source: "MoD Defence Equipment Plan",
    href: "/data/state/defence/equipment",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sc-combat-aircraft": {
    id: "sc-combat-aircraft",
    subtab: "sovereign-capability",
    title: "RAF combat aircraft",
    dataset: "defence.json",
    seriesKey: "combatAircraft",
    timeKey: "year",
    valueKey: "total",
    cadence: "annual",
    direction: "up-good",
    unit: "aircraft",
    format: "number",
    source: "MoD Defence Equipment Plan",
    href: "/data/state/defence/equipment",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sc-defence-spending": {
    id: "sc-defence-spending",
    subtab: "sovereign-capability",
    title: "Defence spending",
    dataset: "defence.json",
    seriesKey: "spendingPctGdp",
    timeKey: "year",
    valueKey: "pct",
    cadence: "annual",
    direction: "up-good",
    unit: "% of GDP",
    format: "percent",
    source: "MoD / NATO",
    href: "/data/state/defence/spending",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sc-ghg-emissions": {
    id: "sc-ghg-emissions",
    subtab: "sovereign-capability",
    title: "Greenhouse gas emissions",
    dataset: "environment.json",
    seriesKey: "ghgEmissions",
    timeKey: "year",
    valueKey: "total",
    cadence: "annual",
    direction: "up-bad",
    unit: "MtCO₂e",
    format: "number",
    source: "DESNZ — UK GHG inventory",
    href: "/data/foundations/environment",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sc-productivity": {
    id: "sc-productivity",
    subtab: "sovereign-capability",
    title: "Output per hour",
    dataset: "productivity.json",
    seriesKey: "levelSeries",
    timeKey: "year",
    valueKey: "gbpPerHour",
    cadence: "annual",
    direction: "up-good",
    unit: "£ / hour",
    format: "currency",
    source: "ONS Labour productivity",
    href: "/data/growth/productivity",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sc-mfg-output": {
    id: "sc-mfg-output",
    subtab: "sovereign-capability",
    title: "Manufacturing output",
    dataset: "mfg-output.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-good",
    unit: "index (2022=100)",
    format: "raw",
    source: "ONS Index of Production (K222)",
    href: "/data/growth/industrial",
    periodLabel: { mom: "vs prior month", q: "vs 3 months ago", y: "vs prior year" },
  },

  "sc-rd-pct-gdp": {
    id: "sc-rd-pct-gdp",
    subtab: "sovereign-capability",
    title: "R&D spending as % of GDP",
    dataset: "research.json",
    seriesKey: "gdpPct",
    timeKey: "year",
    valueKey: "pctGDP",
    cadence: "annual",
    direction: "up-good",
    unit: "% of GDP",
    format: "percent",
    source: "ONS — UK R&D expenditure",
    href: "/data/growth/research",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sc-vc-investment": {
    id: "sc-vc-investment",
    subtab: "sovereign-capability",
    title: "UK VC investment",
    dataset: "startups.json",
    seriesKey: "equity",
    timeKey: "year",
    valueKey: "total",
    cadence: "annual",
    direction: "up-good",
    unit: "£ bn",
    format: "currency",
    source: "British Business Bank / KPMG VPM",
    href: "/data/growth/startups",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sc-high-growth-firms": {
    id: "sc-high-growth-firms",
    subtab: "sovereign-capability",
    title: "High-growth firms",
    dataset: "startups.json",
    seriesKey: "highGrowth",
    timeKey: "year",
    valueKey: "count",
    cadence: "annual",
    direction: "up-good",
    unit: "firms",
    format: "number",
    source: "ONS Business Demography",
    href: "/data/growth/startups",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "sc-iop-chemicals": {
    id: "sc-iop-chemicals",
    subtab: "sovereign-capability",
    title: "Chemicals manufacturing index",
    dataset: "iop-chemicals.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-good",
    unit: "index (2022=100)",
    format: "raw",
    source: "ONS Index of Production (K226)",
    href: "/data/growth/industrial",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "sc-co2-intensity": {
    id: "sc-co2-intensity",
    subtab: "sovereign-capability",
    title: "CO₂ intensity of generation",
    dataset: "co2-intensity.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "intensity",
    cadence: "monthly",
    direction: "up-bad",
    unit: "gCO₂/kWh",
    format: "raw",
    source: "NESO Carbon Intensity API",
    href: "/data/foundations/energy/electricity",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "bd-gigabit-coverage": {
    id: "bd-gigabit-coverage",
    subtab: "construction",
    title: "Gigabit broadband coverage",
    dataset: "infrastructure.json",
    seriesKey: "broadband.gigabit",
    timeKey: "year",
    valueKey: "pct",
    cadence: "annual",
    direction: "up-good",
    unit: "% of UK premises",
    format: "percent",
    source: "Ofcom Connected Nations",
    href: "/data/growth/digital/broadband",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "bd-heat-pumps-bus": {
    id: "bd-heat-pumps-bus",
    subtab: "construction",
    title: "Heat pump installations (BUS)",
    dataset: "heat-pumps-bus.json",
    seriesKey: "monthly",
    timeKey: "month",
    valueKey: "redemptions",
    cadence: "monthly",
    direction: "up-good",
    unit: "grants / month",
    format: "number",
    source: "DESNZ Boiler Upgrade Scheme",
    href: "/data/foundations/energy",
    periodLabel: { mom: "vs prior month", q: "vs 3 months ago", y: "vs prior year" },
  },

  "bd-fttp-coverage": {
    id: "bd-fttp-coverage",
    subtab: "construction",
    title: "FTTP coverage",
    dataset: "infrastructure.json",
    seriesKey: "broadband.fttp",
    timeKey: "year",
    valueKey: "pct",
    cadence: "annual",
    direction: "up-good",
    unit: "% of UK premises",
    format: "percent",
    source: "Ofcom Connected Nations",
    href: "/data/growth/digital/broadband",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "bd-rail-electrification": {
    id: "bd-rail-electrification",
    subtab: "construction",
    title: "Rail route km electrified",
    dataset: "infrastructure.json",
    seriesKey: "rail.infrastructure",
    timeKey: "year",
    valueKey: "electRouteKm",
    cadence: "annual",
    direction: "up-good",
    unit: "route km",
    format: "number",
    source: "Network Rail / ORR",
    href: "/data/growth/transport/rail",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "bd-motorway-km": {
    id: "bd-motorway-km",
    subtab: "construction",
    title: "Motorway network length",
    dataset: "infrastructure.json",
    seriesKey: "roads.length",
    timeKey: "year",
    valueKey: "motorwaysKm",
    cadence: "annual",
    direction: "up-good",
    unit: "km",
    format: "number",
    source: "DfT Road Lengths Statistics",
    href: "/data/growth/transport/roads",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "bd-reservoir-capacity": {
    id: "bd-reservoir-capacity",
    subtab: "construction",
    title: "Reservoir capacity",
    dataset: "reservoirs.json",
    seriesKey: "cumulativeCapacity",
    timeKey: "year",
    valueKey: "capacityBnL",
    cadence: "annual",
    direction: "up-good",
    unit: "billion litres",
    format: "number",
    source: "EA / water companies",
    href: "/data/foundations/water/reservoirs",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "bd-brick-deliveries": {
    id: "bd-brick-deliveries",
    subtab: "construction",
    title: "Brick deliveries (SA)",
    dataset: "housing-supply.json",
    seriesKey: "brickDeliveries",
    timeKey: "month",
    valueKey: "saDeliveries",
    cadence: "monthly",
    direction: "up-good",
    unit: "millions / month",
    format: "number",
    source: "DESNZ — Construction Building Materials, Table 9a",
    href: "/data/foundations/housing/supply",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "bd-epc-new-builds": {
    id: "bd-epc-new-builds",
    subtab: "construction",
    title: "EPC new-build lodgements",
    dataset: "housing-supply.json",
    seriesKey: "epcNewBuilds",
    timeKey: "quarter",
    valueKey: "lodgements",
    cadence: "quarterly",
    direction: "up-good",
    unit: "lodgements / quarter",
    format: "number",
    source: "MHCLG EPC register, Table NB1",
    href: "/data/foundations/housing/supply",
    periodLabel: {
      mom: "vs prior quarter",
      q: "vs prior quarter",
      y: "vs prior year",
    },
  },

  "bd-battery-storage": {
    id: "bd-battery-storage",
    subtab: "construction",
    title: "Battery storage capacity (de-rated)",
    dataset: "battery-storage.json",
    seriesKey: "annual",
    timeKey: "year",
    valueKey: "mw",
    cadence: "annual",
    direction: "up-good",
    unit: "MW",
    format: "number",
    source: "NESO Capacity Market Register",
    href: "/data/foundations/energy/electricity",
    periodLabel: {
      mom: "vs prior year",
      q: "vs prior year",
      y: "vs prior year",
    },
  },

  // ── Quality of Life ───────────────────────────────────────────────

  "ql-real-wages-annual": {
    id: "ql-real-wages-annual",
    subtab: "quality-of-life",
    title: "Real median pay",
    dataset: "jobs.json",
    seriesKey: "realEarningsTrend",
    timeKey: "year",
    valueKey: "realMedian",
    cadence: "annual",
    direction: "up-good",
    unit: "£ (real, 2025 prices)",
    format: "currency",
    source: "ONS ASHE, deflated by CPI",
    href: "/data/growth/jobs/earnings",
    periodLabel: {
      mom: "vs prior year",
      q: "vs prior year",
      y: "vs prior year",
    },
  },

  "ql-real-wages-monthly": {
    id: "ql-real-wages-monthly",
    subtab: "quality-of-life",
    title: "Real wages YoY",
    dataset: "real-wages-monthly.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "realYoY",
    cadence: "monthly",
    direction: "up-good",
    unit: "% YoY",
    format: "percent",
    source: "ONS AWE / CPIH",
    href: "/data/growth/jobs/earnings",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "ql-house-price": {
    id: "ql-house-price",
    subtab: "quality-of-life",
    title: "UK average house price",
    dataset: "house-price-index.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "avgPrice",
    cadence: "monthly",
    direction: "neutral",
    unit: "£",
    format: "currency",
    source: "HM Land Registry, UK HPI",
    href: "/data/foundations/housing/prices",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "ql-cpih-inflation": {
    id: "ql-cpih-inflation",
    subtab: "quality-of-life",
    title: "CPIH inflation",
    dataset: "cpih.json",
    seriesKey: "series",
    timeKey: "time",
    valueKey: "yoy",
    enrich: { type: "yoy", baseValueKey: "CP00" },
    cadence: "monthly",
    direction: "neutral",
    unit: "% YoY",
    format: "percent",
    source: "ONS CPIH",
    href: "/data/spending/spending/moneySupply",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  // ── Cross-cutting (Spending pillar) ───────────────────────────────

  "qol-services-output": {
    id: "qol-services-output",
    subtab: "quality-of-life",
    title: "Services output",
    dataset: "services-output.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-good",
    unit: "index (2022=100)",
    format: "raw",
    source: "ONS Index of Services (S2KU)",
    href: "/data/spending/spending/gdp",
    periodLabel: { mom: "vs prior month", q: "vs 3 months ago", y: "vs prior year" },
  },

  "qol-construction-output": {
    id: "qol-construction-output",
    subtab: "construction",
    title: "Construction output",
    dataset: "construction-output.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-good",
    unit: "£m / month",
    format: "currency",
    source: "ONS Construction Output (KFAP)",
    href: "/data/foundations/housing/supply",
    periodLabel: { mom: "vs prior month", q: "vs 3 months ago", y: "vs prior year" },
  },

  "ql-avg-hours": {
    id: "ql-avg-hours",
    subtab: "quality-of-life",
    title: "Average weekly hours",
    dataset: "avg-weekly-hours.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "neutral",
    unit: "hours / week",
    format: "raw",
    source: "ONS LFS (YBUS)",
    href: "/data/growth/jobs/overview",
    periodLabel: { mom: "vs prior month", q: "vs 3 months ago", y: "vs prior year" },
  },

  "qol-monthly-gdp": {
    id: "qol-monthly-gdp",
    subtab: "quality-of-life",
    title: "GDP (monthly index)",
    dataset: "monthly-gdp.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-good",
    unit: "index (2022=100)",
    format: "raw",
    source: "ONS Monthly GDP (ECY2)",
    href: "/data/spending/spending/gdp",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "ql-unemployment-rate": {
    id: "ql-unemployment-rate",
    subtab: "quality-of-life",
    title: "Unemployment rate",
    dataset: "unemployment-rate.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-bad",
    unit: "%",
    format: "percent",
    source: "ONS LFS (MGSX)",
    href: "/data/growth/jobs/unemployment",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "sd-public-sector-debt": {
    id: "sd-public-sector-debt",
    subtab: "service-delivery",
    title: "Public sector net debt",
    dataset: "public-sector-debt.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-bad",
    unit: "% of GDP",
    format: "percent",
    source: "ONS PSND (HF6X)",
    href: "/data/spending/spending/borrowing",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "ql-gilt-yield-10y": {
    id: "ql-gilt-yield-10y",
    subtab: "quality-of-life",
    title: "10-year gilt yield",
    dataset: "borrowing.json",
    seriesKey: "giltYields",
    timeKey: "month",
    valueKey: "y10",
    cadence: "monthly",
    direction: "up-bad",
    unit: "% (10-year nominal)",
    format: "percent",
    source: "Bank of England, gilt yield curve",
    href: "/data/spending/spending/borrowing",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "ql-mortgage-rate": {
    id: "ql-mortgage-rate",
    subtab: "quality-of-life",
    title: "Average mortgage rate",
    dataset: "money-supply.json",
    seriesKey: "mortgageRate",
    timeKey: "month",
    valueKey: "rate",
    cadence: "monthly",
    direction: "up-bad",
    unit: "% (effective rate)",
    format: "percent",
    source: "Bank of England (CFM)",
    href: "/data/spending/personalFinance",
    periodLabel: { mom: "vs prior month", q: "vs 3 months ago", y: "vs prior year" },
  },

  "ql-mortgage-approvals": {
    id: "ql-mortgage-approvals",
    subtab: "quality-of-life",
    title: "Mortgage approvals (house purchase)",
    dataset: "money-supply.json",
    seriesKey: "mortgageApprovals",
    timeKey: "month",
    valueKey: "approvals",
    cadence: "monthly",
    direction: "up-good",
    unit: "/ month",
    format: "number",
    source: "Bank of England Bankstats",
    href: "/data/spending/personalFinance",
    periodLabel: { mom: "vs prior month", q: "vs 3 months ago", y: "vs prior year" },
  },

  "ql-net-migration": {
    id: "ql-net-migration",
    subtab: "quality-of-life",
    title: "Net migration",
    dataset: "immigration.json",
    seriesKey: "netMigration",
    timeKey: "year",
    valueKey: "net",
    cadence: "annual",
    direction: "neutral",
    unit: "thousands",
    format: "raw",
    source: "ONS Long-Term International Migration",
    href: "/data/state/immigration",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "ql-life-expectancy": {
    id: "ql-life-expectancy",
    subtab: "quality-of-life",
    title: "Life expectancy at birth (female)",
    dataset: "health-outcomes.json",
    seriesKey: "lifeExpectancy",
    timeKey: "year",
    valueKey: "female",
    cadence: "annual",
    direction: "up-good",
    unit: "years",
    format: "raw",
    source: "ONS National Life Tables",
    href: "/data/foundations/healthcare/outcomes",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "ql-healthy-life-expectancy": {
    id: "ql-healthy-life-expectancy",
    subtab: "quality-of-life",
    title: "Healthy life expectancy (male)",
    dataset: "health-outcomes.json",
    seriesKey: "healthyLifeExpectancy",
    timeKey: "year",
    valueKey: "maleHealthy",
    cadence: "annual",
    direction: "up-good",
    unit: "years",
    format: "raw",
    source: "ONS Health State Life Expectancies",
    href: "/data/foundations/healthcare/outcomes",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "ql-knife-crime": {
    id: "ql-knife-crime",
    subtab: "quality-of-life",
    title: "Knife crime offences",
    dataset: "knife-crime-quarterly.json",
    seriesKey: "quarterly",
    timeKey: "quarter",
    valueKey: "offences",
    cadence: "quarterly",
    direction: "up-bad",
    unit: "offences / quarter",
    format: "number",
    source: "ONS Crime in England and Wales",
    href: "/data/foundations/safety",
    periodLabel: { mom: "vs prior quarter", q: "vs prior quarter", y: "vs prior year" },
  },

  "ql-violent-crime": {
    id: "ql-violent-crime",
    subtab: "quality-of-life",
    title: "Violent crime",
    dataset: "safety.json",
    seriesKey: "violentCrime",
    timeKey: "year",
    valueKey: "total",
    cadence: "annual",
    direction: "up-bad",
    unit: "thousand offences",
    format: "number",
    source: "ONS Crime Survey for England & Wales",
    href: "/data/foundations/safety",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "ql-fear-of-crime": {
    id: "ql-fear-of-crime",
    subtab: "quality-of-life",
    title: "Feel unsafe walking alone after dark",
    dataset: "safety.json",
    seriesKey: "fearOfCrime",
    timeKey: "year",
    valueKey: "unsafeAlone",
    cadence: "annual",
    direction: "up-bad",
    unit: "%",
    format: "percent",
    source: "ONS CSEW",
    href: "/data/foundations/safety",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "ql-suicide-rate": {
    id: "ql-suicide-rate",
    subtab: "quality-of-life",
    title: "Suicide rate",
    dataset: "mental-health.json",
    seriesKey: "suicideRate",
    timeKey: "year",
    valueKey: "total",
    cadence: "annual",
    direction: "up-bad",
    unit: "per 100,000",
    format: "raw",
    source: "ONS Suicides in the UK",
    href: "/data/foundations/healthcare/mental",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "ql-births-quarterly": {
    id: "ql-births-quarterly",
    subtab: "quality-of-life",
    title: "Live births (quarterly)",
    dataset: "births-quarterly.json",
    seriesKey: "quarterly",
    timeKey: "quarter",
    valueKey: "births",
    cadence: "quarterly",
    direction: "up-good",
    unit: "births / quarter",
    format: "number",
    source: "ONS Quarterly births",
    href: "/data/foundations/family",
    periodLabel: { mom: "vs prior quarter", q: "vs prior quarter", y: "vs prior year" },
  },

  "ql-tfr": {
    id: "ql-tfr",
    subtab: "quality-of-life",
    title: "Total fertility rate",
    dataset: "family.json",
    seriesKey: "tfrByOrder",
    timeKey: "year",
    valueKey: "tfrTotal",
    cadence: "annual",
    direction: "up-good",
    unit: "births / woman",
    format: "raw",
    source: "ONS Vital Statistics",
    href: "/data/foundations/family",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "ql-household-size": {
    id: "ql-household-size",
    subtab: "quality-of-life",
    title: "Average household size",
    dataset: "family.json",
    seriesKey: "householdSizeSeries",
    timeKey: "year",
    valueKey: "size",
    cadence: "annual",
    direction: "neutral",
    unit: "people",
    format: "raw",
    source: "ONS",
    href: "/data/foundations/family",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "ql-pm25": {
    id: "ql-pm25",
    subtab: "quality-of-life",
    title: "Air quality (PM2.5)",
    dataset: "environment.json",
    seriesKey: "pm25",
    timeKey: "year",
    valueKey: "mean",
    cadence: "annual",
    direction: "up-bad",
    unit: "μg/m³ (mean)",
    format: "raw",
    source: "DEFRA — UK air quality stats",
    href: "/data/foundations/environment",
    periodLabel: { mom: "vs prior year", q: "vs prior year", y: "vs prior year" },
  },

  "ql-employment-rate": {
    id: "ql-employment-rate",
    subtab: "quality-of-life",
    title: "Employment rate (16-64)",
    dataset: "employment-rate.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-good",
    unit: "%",
    format: "percent",
    source: "ONS LFS (LF24)",
    href: "/data/growth/jobs/overview",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "ql-cpi-inflation": {
    id: "ql-cpi-inflation",
    subtab: "quality-of-life",
    title: "CPI inflation (BoE target metric)",
    dataset: "cpi-inflation.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "neutral",
    unit: "% YoY",
    format: "percent",
    source: "ONS CPI (D7G7)",
    href: "/data/spending/spending/moneySupply",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "ql-economic-inactivity": {
    id: "ql-economic-inactivity",
    subtab: "quality-of-life",
    title: "Economic inactivity (16-64)",
    dataset: "economic-inactivity.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-bad",
    unit: "%",
    format: "percent",
    source: "ONS LFS (LF2S)",
    href: "/data/growth/jobs/overview",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  "ql-retail-sales": {
    id: "ql-retail-sales",
    subtab: "quality-of-life",
    title: "Retail sales volume",
    dataset: "retail-sales.json",
    seriesKey: "monthly",
    timeKey: "period",
    valueKey: "value",
    cadence: "monthly",
    direction: "up-good",
    unit: "index (2022=100)",
    format: "raw",
    source: "ONS Retail Sales Index (J5EL)",
    href: "/data/growth/jobs/overview",
    periodLabel: {
      mom: "vs prior month",
      q: "vs 3 months ago",
      y: "vs prior year",
    },
  },

  // More metrics to be added as Phase 3b/3c fetches land.
};

/** Metrics filtered by sub-tab, in display order. */
export function metricsForSubtab(subtab) {
  return Object.values(METRICS).filter((m) => m.subtab === subtab);
}
